### PR TITLE
Add publish snapshots to maven via GHA

### PR DESCRIPTION
**Pull request by rupal-bq**
### Description
- Added publish snapshots to maven via GHA

### Issues Resolved
https://github.com/opensearch-project/reporting/issues/648

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Hi @rupal-bq,
Can you post the output like the one specified under `Testing` in the issue?
Just to make sure we have right group id and artifacts.
Thanks!

**Comment by rupal-bq** [comment]
> Hi @rupal-bq, Can you post the output like the one specified under `Testing` in the issue? Just to make sure we have right group id and artifacts. Thanks!

Hi Sayali, this is the local testing output.
```
maharup@b0f1d879dff7 reporting % ./gradlew publishPluginZipPublicationToSnapshotsRepository
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Mac OS X 13.2 (x86_64)
  JDK Version           : 11 (Amazon Corretto JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
  Random Testing Seed   : 39A74EF54FD3DC7A
  In FIPS 140 mode      : false
=======================================

> Task :compileKotlin
w: /Users/maharup/GitRepoWorkspace/reporting/src/main/kotlin/org/opensearch/reportsscheduler/index/ReportDefinitionsIndex.kt: (68, 18): 'mapping(String!, XContentType!): CreateIndexRequest!' is deprecated. Deprecated in Java
w: /Users/maharup/GitRepoWorkspace/reporting/src/main/kotlin/org/opensearch/reportsscheduler/index/ReportDefinitionsIndex.kt: (69, 18): 'settings(String!, XContentType!): CreateIndexRequest!' is deprecated. Deprecated in Java
w: /Users/maharup/GitRepoWorkspace/reporting/src/main/kotlin/org/opensearch/reportsscheduler/index/ReportInstancesIndex.kt: (68, 18): 'mapping(String!, XContentType!): CreateIndexRequest!' is deprecated. Deprecated in Java
w: /Users/maharup/GitRepoWorkspace/reporting/src/main/kotlin/org/opensearch/reportsscheduler/index/ReportInstancesIndex.kt: (69, 18): 'settings(String!, XContentType!): CreateIndexRequest!' is deprecated. Deprecated in Java

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 24s
11 actionable tasks: 6 executed, 5 up-to-date
maharup@b0f1d879dff7 reporting % find snapshots | sort 
snapshots
snapshots/org
snapshots/org/opensearch
snapshots/org/opensearch/plugin
snapshots/org/opensearch/plugin/opensearch-reports-scheduler
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/maven-metadata.xml
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/maven-metadata.xml.sha512
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.181216-1.pom
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.181216-1.pom.md5
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.181216-1.pom.sha1
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.181216-1.pom.sha256
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.181216-1.pom.sha512
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.181216-1.zip
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.181216-1.zip.md5
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.181216-1.zip.sha1
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.181216-1.zip.sha256
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.181216-1.zip.sha512
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.192011-2.pom
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.192011-2.pom.md5
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.192011-2.pom.sha1
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.192011-2.pom.sha256
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.192011-2.pom.sha512
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.192011-2.zip
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.192011-2.zip.md5
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.192011-2.zip.sha1
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.192011-2.zip.sha256
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/3.0.0.0-SNAPSHOT/opensearch-reports-scheduler-3.0.0.0-20230220.192011-2.zip.sha512
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/maven-metadata.xml
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/opensearch-reports-scheduler/maven-metadata.xml.sha512
maharup@b0f1d879dff7 reporting % 
```

**Comment by gaiksaya** [comment]
Thanks! LGTM. Will work on adding the role.

**Review by gaiksaya — APPROVED** [review]
Added `PUBLISH_SNAPSHOTS_ROLE` secret

**Review by ps48 — APPROVED** [review]

**Review by kavithacm — APPROVED** [review]

**Review by YANG-DB — APPROVED** [review]

**Pull request merged**
